# Use new trusty images, should yield newer compilers and packages
dist: trusty
sudo: false
language: cpp

# skip the install step, we have no dependencies
install: true

# set up a build directory and run cmake; "make all" should then work then work
before_script:
  - pwd
  - mkdir build
  - cd build
  - cmake ..

# build using make, then run Eidos and SLiM tests
# builds can take more than 10 minutes so we use travis_wait
script:
  - pwd
  - travis_wait make
  - ./eidos -testEidos
  - ./slim -testEidos
  - ./slim -testSLiM

# use gcc; this probably doesn't matter since we call make anyway
# it would be nice to try different gcc versions, but that is presently quite complex
# see https://stackoverflow.com/questions/29312015/building-with-more-than-one-version-of-a-compiler
# see https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
compiler:
  - gcc

# linux and os x builds
os:
  - linux
  - osx

# test only the master branch for now; add other branches as needed
branches:
  only:
    - master

# notify me by email after all builds
notifications:
  email:
    on_success: always
    on_failure: always

